//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAVSEM {
	
	
	public partial class Administrador {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.HyperLink hpHome;
		
		protected System.Web.UI.WebControls.HyperLink hpUsuario;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnMosAUs;
		
		protected System.Web.UI.WebControls.DataGrid tbUsers;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnMosAPe;
		
		protected System.Web.UI.WebControls.DataGrid tbProductos;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnMosAMa;
		
		protected System.Web.UI.WebControls.DataGrid tbMensajes;
	}
}
