//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAVSEM {
	
	
	public partial class Index {
		
		protected System.Web.UI.WebControls.HyperLink linkIndex;
		
		protected System.Web.UI.WebControls.TextBox txtBuscar;
		
		protected System.Web.UI.WebControls.ImageButton imbtnBuscar;
		
		protected System.Web.UI.WebControls.Login lgUser;
		
		protected System.Web.UI.WebControls.Panel userData;
		
		protected System.Web.UI.WebControls.Label lblBienvenido;
		
		protected System.Web.UI.WebControls.LinkButton linkVenta;
		
		protected System.Web.UI.WebControls.LinkButton linkCompra;
		
		protected System.Web.UI.WebControls.LinkButton linkGestion;
		
		protected System.Web.UI.WebControls.LinkButton linkAdministrador;
		
		protected System.Web.UI.WebControls.LinkButton lnkbtnSalir;
		
		protected System.Web.UI.WebControls.HyperLink linkInicio;
		
		protected System.Web.UI.WebControls.HyperLink linkVenderProductos;
		
		protected System.Web.UI.WebControls.HyperLink linkAyuda;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder cl;
	}
}
