//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAVSEM {
	
	
	public partial class Registro {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.HyperLink hpHome;
		
		protected System.Web.UI.WebControls.TextBox txtUsuario;
		
		protected System.Web.UI.WebControls.TextBox txtContrasenia;
		
		protected System.Web.UI.WebControls.TextBox txtContraseniaRep;
		
		protected System.Web.UI.WebControls.TextBox txtNombre;
		
		protected System.Web.UI.WebControls.TextBox txtApellidos;
		
		protected System.Web.UI.WebControls.TextBox txtDireccion;
		
		protected System.Web.UI.WebControls.TextBox txtCP;
		
		protected System.Web.UI.WebControls.TextBox txtTelefono;
		
		protected System.Web.UI.WebControls.TextBox txtCorreo;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl myPDF;
		
		protected System.Web.UI.WebControls.CheckBox cbxAceptar;
		
		protected System.Web.UI.WebControls.Label lbCondicion;
		
		protected System.Web.UI.WebControls.Button btnRegistrar;
	}
}
