//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAVSEM {
	
	
	public partial class Ayuda {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.HyperLink hpHome;
		
		protected System.Web.UI.WebControls.Panel userSession;
		
		protected System.Web.UI.WebControls.TextBox txtAyTexto;
		
		protected System.Web.UI.WebControls.TextBox txtAyMensaje;
		
		protected System.Web.UI.WebControls.Button btnAyEnviar;
		
		protected System.Web.UI.WebControls.Label messageError;
	}
}
