//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAVSEM {
	
	
	public partial class Buscar {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.HyperLink hpHome;
		
		protected System.Web.UI.WebControls.Label lblBusqueda;
		
		protected System.Web.UI.WebControls.GridView tbBusqueda;
		
		protected System.Web.UI.WebControls.ImageButton gvImage;
		
		protected System.Web.UI.WebControls.LinkButton gvlblProducto;
		
		protected System.Web.UI.WebControls.Label gvlblCantidad;
		
		protected System.Web.UI.WebControls.Label gvlblPrecio;
		
		protected System.Web.UI.WebControls.Label gvlblFecha;
		
		protected System.Web.UI.WebControls.Label gvlblVendedor;
		
		protected System.Web.UI.WebControls.Button btnVer;
	}
}
