//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAVSEM {
	
	
	public partial class Compras {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.HyperLink hpHome;
		
		protected System.Web.UI.WebControls.HyperLink hpUsuario;
		
		protected System.Web.UI.WebControls.Panel productorModo;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnMosRec;
		
		protected System.Web.UI.WebControls.DataGrid tbRecibidos;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnMosRea;
		
		protected System.Web.UI.WebControls.DataGrid tbRealizados;
		
		protected System.Web.UI.WebControls.Label indicador;
	}
}
