//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAVSEM {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Panel producto1;
		
		protected System.Web.UI.WebControls.ImageButton imgProducto1;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnProducto1;
		
		protected System.Web.UI.WebControls.Label lblProducto1;
		
		protected System.Web.UI.WebControls.Panel producto2;
		
		protected System.Web.UI.WebControls.ImageButton imgProducto2;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnProducto2;
		
		protected System.Web.UI.WebControls.Label lblProducto2;
		
		protected System.Web.UI.WebControls.Panel producto3;
		
		protected System.Web.UI.WebControls.ImageButton imgProducto3;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnProducto3;
		
		protected System.Web.UI.WebControls.Label lblProducto3;
		
		protected System.Web.UI.WebControls.Panel producto4;
		
		protected System.Web.UI.WebControls.ImageButton imgProducto4;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnProducto4;
		
		protected System.Web.UI.WebControls.Label lblProducto4;
		
		protected System.Web.UI.WebControls.Panel producto5;
		
		protected System.Web.UI.WebControls.ImageButton imgProducto5;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnProducto5;
		
		protected System.Web.UI.WebControls.Label lblProducto5;
		
		protected System.Web.UI.WebControls.Panel producto6;
		
		protected System.Web.UI.WebControls.ImageButton imgProducto6;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnProducto6;
		
		protected System.Web.UI.WebControls.Label lblProducto6;
		
		protected System.Web.UI.WebControls.Panel producto7;
		
		protected System.Web.UI.WebControls.ImageButton imgProducto7;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnProducto7;
		
		protected System.Web.UI.WebControls.Label lblProducto7;
		
		protected System.Web.UI.WebControls.Panel producto8;
		
		protected System.Web.UI.WebControls.ImageButton imgProducto8;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnProducto8;
		
		protected System.Web.UI.WebControls.Label lblProducto8;
		
		protected System.Web.UI.WebControls.Panel producto9;
		
		protected System.Web.UI.WebControls.ImageButton imgProducto9;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnProducto9;
		
		protected System.Web.UI.WebControls.Label lblProducto9;
		
		protected System.Web.UI.WebControls.Panel producto10;
		
		protected System.Web.UI.WebControls.ImageButton imgProducto10;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnProducto10;
		
		protected System.Web.UI.WebControls.Label lblProducto10;
	}
}
