//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAVSEM {
	
	
	public partial class GestionUsuario {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.HyperLink hpHome;
		
		protected System.Web.UI.WebControls.Label errorUserGes;
		
		protected System.Web.UI.WebControls.Label lblGesUser;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesUser;
		
		protected System.Web.UI.WebControls.Label lblGesUsuarioMod;
		
		protected System.Web.UI.WebControls.TextBox txtGesUser;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesUserConfirm;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesPass;
		
		protected System.Web.UI.WebControls.Label lblGesOldPassMod;
		
		protected System.Web.UI.WebControls.TextBox txtGesOldPass;
		
		protected System.Web.UI.WebControls.Label lblGesPassMod;
		
		protected System.Web.UI.WebControls.TextBox txtGesPass;
		
		protected System.Web.UI.WebControls.Label lblGesPassConfMod;
		
		protected System.Web.UI.WebControls.TextBox txtGesPassConfirm;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesPassConfirm;
		
		protected System.Web.UI.WebControls.Label lblGesNombre;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesNombre;
		
		protected System.Web.UI.WebControls.Label lblGesNombreMod;
		
		protected System.Web.UI.WebControls.TextBox txtGesNombre;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesNombreConfirm;
		
		protected System.Web.UI.WebControls.Label lblGesApellido;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesApellido;
		
		protected System.Web.UI.WebControls.Label lblGesApellidoMod;
		
		protected System.Web.UI.WebControls.TextBox txtGesApellido;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesApellidoConfirm;
		
		protected System.Web.UI.WebControls.Label lblGesDireccion;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesDireccion;
		
		protected System.Web.UI.WebControls.Label lblGesDireccionMod;
		
		protected System.Web.UI.WebControls.TextBox txtGesDireccion;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesDireccionConfirm;
		
		protected System.Web.UI.WebControls.Label lblGesCP;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesCP;
		
		protected System.Web.UI.WebControls.Label lblGesCPMod;
		
		protected System.Web.UI.WebControls.TextBox txtGesCP;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesCPConfirm;
		
		protected System.Web.UI.WebControls.Label lblGesTelefono;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesTelefono;
		
		protected System.Web.UI.WebControls.Label lblGesTelefonoMod;
		
		protected System.Web.UI.WebControls.TextBox txtGesTelefono;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesTelefonoConfirm;
		
		protected System.Web.UI.WebControls.Label lblGesCorreo;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesCorreo;
		
		protected System.Web.UI.WebControls.Label lblGesCorreoMod;
		
		protected System.Web.UI.WebControls.TextBox txtGesCorreo;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnGesCorreoConfirm;
		
		protected System.Web.UI.WebControls.DataGrid tbHistorial;
	}
}
