//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAVSEM {
	
	
	public partial class Producto {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Label tituloProducto;
		
		protected System.Web.UI.WebControls.Image imageProducto;
		
		protected System.Web.UI.WebControls.Label precioProducto;
		
		protected System.Web.UI.WebControls.Label unidadProducto;
		
		protected System.Web.UI.WebControls.Label uDisProducto;
		
		protected System.Web.UI.WebControls.Label comProducto;
		
		protected System.Web.UI.WebControls.Label VendedorProducto;
		
		protected System.Web.UI.WebControls.Label emailProducto;
		
		protected System.Web.UI.WebControls.TextBox txtUniCompra;
		
		protected System.Web.UI.WebControls.LinkButton lkbtnCalcular;
		
		protected System.Web.UI.WebControls.TextBox txtCostTotal;
		
		protected System.Web.UI.WebControls.Label errorCompra;
		
		protected System.Web.UI.WebControls.Button btnPedir;
	}
}
