//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAVSEM {
	
	
	public partial class RegistroVendedor {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.HyperLink hpHome;
		
		protected System.Web.UI.WebControls.Panel sessionNoStart;
		
		protected System.Web.UI.WebControls.TextBox txtRegUser;
		
		protected System.Web.UI.WebControls.TextBox txtRegPass;
		
		protected System.Web.UI.WebControls.HyperLink linkRegistro;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl myPDF;
		
		protected System.Web.UI.WebControls.CheckBox cbxAceptar;
		
		protected System.Web.UI.WebControls.Label lbCondicion;
		
		protected System.Web.UI.WebControls.Button btnRegReg;
	}
}
