//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAVSEM {
	
	
	public partial class Ventas {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.HyperLink hpHome;
		
		protected System.Web.UI.WebControls.HyperLink hpUsuario;
		
		protected System.Web.UI.WebControls.Button btnAniadir;
		
		protected System.Web.UI.WebControls.Panel panelAniadir;
		
		protected System.Web.UI.WebControls.TextBox txtNomProd;
		
		protected System.Web.UI.WebControls.TextBox txtUniDisp;
		
		protected System.Web.UI.WebControls.TextBox txtTipUni;
		
		protected System.Web.UI.WebControls.TextBox txtPrecio;
		
		protected System.Web.UI.WebControls.TextBox txtComenProd;
		
		protected System.Web.UI.WebControls.FileUpload fuImage;
		
		protected System.Web.UI.WebControls.Button btnUploadImage;
		
		protected System.Web.UI.WebControls.Image imgPreview;
		
		protected System.Web.UI.WebControls.Label lblErrorPublicar;
		
		protected System.Web.UI.WebControls.Button btnPublicar;
		
		protected System.Web.UI.WebControls.GridView tbVentas;
		
		protected System.Web.UI.WebControls.Label gvlblID;
		
		protected System.Web.UI.WebControls.Label gvlblFecha;
		
		protected System.Web.UI.WebControls.Label gvlblComprado;
		
		protected System.Web.UI.WebControls.TextBox gvtxtNombre;
		
		protected System.Web.UI.WebControls.Label gvlblNombre;
		
		protected System.Web.UI.WebControls.TextBox gvtxtPrecio;
		
		protected System.Web.UI.WebControls.Label gvlblPrecio;
		
		protected System.Web.UI.WebControls.TextBox gvtxtUVenta;
		
		protected System.Web.UI.WebControls.Label gvlblUVenta;
		
		protected System.Web.UI.WebControls.TextBox gvtxtDisponibles;
		
		protected System.Web.UI.WebControls.Label gvlblDisponibles;
		
		protected System.Web.UI.WebControls.TextBox gvtxtComentario;
		
		protected System.Web.UI.WebControls.Label gvlblComentario;
		
		protected System.Web.UI.WebControls.Label gvlblFoto;
		
		protected System.Web.UI.WebControls.FileUpload gvfuFoto;
		
		protected System.Web.UI.WebControls.Image gvImage;
		
		protected System.Web.UI.WebControls.Label lblErrorPrueba;
	}
}
